version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: nestcrud
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/../pgData:/var/lib/postgresql/data